AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an S3 Bucket with Intelligent Tiering

Parameters:
  BucketName:
    Type: String

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      IntelligentTieringConfigurations:
        - Id: Default
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90

Outputs:
  BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref MyS3Bucket
