AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an S3 Bucket with Intelligent Tiering

Parameters:
  BucketName:
    Type: String

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      IntelligentTieringConfigurations:
        - Id: Default
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 7 # Expired versions will be removed after 7 days
            ExpiredObjectDeleteMarker: true # Expired objects w/o a current version will be removed

Outputs:
  BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref MyS3Bucket
